version: '3.8'
services:
  webserver:
    build:
          context: .
          dockerfile: Dockerfile  # Specify the Dockerfile name if it's not named 'Dockerfile'
    ports:
      - "9090:9090"
    volumes:
      - ./app:/app
    restart: always