version: '3.8'
services:
  webserver:
    image: kwangko/test:v1.0
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - "9090:8080"
    volumes:
      - myjar:/app  # Map the local 'app' directory to the '/app' directory in the container
    user: "1000:1000"
    restart: always
volumes:
  myjar: {}
